# POST http://localhost:4000/auth/register HTTP/1.1
# content-type: application/json

# {
#    "email": "soufiane33@arhlabi.com",
#    "password": "randompass",
#    "displayName": "Soufiane"
# }

# POST http://localhost:4000/auth/login HTTP/1.1
# content-type: application/json

# {
#    "email": "gatewayarhlabi2@gmail.com",
#    "password": "randompass"
# }
#"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMTFlNjg1YS0xOTI0LTQ3NGYtYjFkOC02ZjYyZTkxNjg1ZWMiLCJlbWFpbCI6ImdhdGV3YXlhcmhsYWJpMkBnbWFpbC5jb20iLCJpYXQiOjE3NzIwODc0ODAsImV4cCI6MTc3MjE3Mzg4MH0.C6uGN0JRAEAgacrSOJETf0g5uczzOIrHVSe6JwCNCcE"

# POST http://localhost:4000/auth/refresh HTTP/1.1
# content-type: application/json

# {
#    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMTFlNjg1YS0xOTI0LTQ3NGYtYjFkOC02ZjYyZTkxNjg1ZWMiLCJ0b2tlbklkIjoiNTgxNTg4NGMtYTQ5ZC00N2U0LTllMzMtMTBiYTQ3OWRjNGZkIiwiaWF0IjoxNzcwODAwNDI2LCJleHAiOjE3NzA4ODY4MjZ9.sq-RVxUoWpBPV1O9IXOrGU7xbeGZpI8qXDJFzhWK6bA"
# }

# POST http://localhost:4000/auth/revoke HTTP/1.1
# content-type: application/json

# {
#    "userId": "e11e685a-1924-474f-b1d8-6f62e91685ec"
# }

# GET http://localhost:4000/users/ HTTP/1.1

GET http://localhost:4000/users/e11e685a-1924-474f-b1d8-6f62e91685ec HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMTYzYTA2ZC1hZTA5LTRlZjEtOWRlMi1kZTY4ZWM1YTZmODQiLCJlbWFpbCI6InNvdWZpYW5lMzNAYXJobGFiaS5jb20iLCJpYXQiOjE3NzIwODc4MzksImV4cCI6MTc3MjE3NDIzOX0.zWzv9257-M18cFTPJuk47tfvpAuyDp0Go0pagaK23vU


# POST http://localhost:4000/users/ HTTP/1.1
# content-type: application/json

# {
#   "email": "gatewayarhlabi4@gmail.com",
#   "displayName": "arh"
# }


# GET http://localhost:4000/users/search?query=soufiane&limit=4 HTTP/1.1
# Host: localhost:4000
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMTYzYTA2ZC1hZTA5LTRlZjEtOWRlMi1kZTY4ZWM1YTZmODQiLCJlbWFpbCI6InNvdWZpYW5lMzNAYXJobGFiaS5jb20iLCJpYXQiOjE3NzIwODc4MzksImV4cCI6MTc3MjE3NDIzOX0.zWzv9257-M18cFTPJuk47tfvpAuyDp0Go0pagaK23vU

#POST http://localhost:4000/auth/register HTTP/1.1
#content-type: application/json

#{
#   "email": "gatewayarhlabi2@gmail.com",
#   "password": "randompass",
#   "displayName": "Soufiane"
#}



