# POST http://localhost:4003/auth/register HTTP/1.1
# content-type: application/json

# {
#    "email": "soufiane@arhlabi.com",
#    "password": "randompass",
#    "displayName": "Soufiane"
# }

# POST http://localhost:4000/auth/login HTTP/1.1
# content-type: application/json

# {
#    "email": "gatewayarhlabi2@gmail.com",
#    "password": "randompass"
# }


# POST http://localhost:4000/auth/refresh HTTP/1.1
# content-type: application/json

# {
#    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMTFlNjg1YS0xOTI0LTQ3NGYtYjFkOC02ZjYyZTkxNjg1ZWMiLCJ0b2tlbklkIjoiNTgxNTg4NGMtYTQ5ZC00N2U0LTllMzMtMTBiYTQ3OWRjNGZkIiwiaWF0IjoxNzcwODAwNDI2LCJleHAiOjE3NzA4ODY4MjZ9.sq-RVxUoWpBPV1O9IXOrGU7xbeGZpI8qXDJFzhWK6bA"
# }

POST http://localhost:4000/auth/revoke HTTP/1.1
content-type: application/json

{
   "userId": "e11e685a-1924-474f-b1d8-6f62e91685ec"
}


#POST http://localhost:4000/auth/register HTTP/1.1
#content-type: application/json

#{
#   "email": "gatewayarhlabi2@gmail.com",
#   "password": "randompass",
#   "displayName": "Soufiane"
#}



